### ISSUE TITLE
python setup.py bdist_wheel did not run successfully.

### ISSUE THREAD

**Issue by ODOshmocke** [Blueshoe/python-healthcard#7]
I try to install the package but i get this Error:
 error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      building 'smartcard.scard._scard' extension
      swigging smartcard/scard/scard.i to smartcard/scard/scard_wrap.c
      swig.exe -python -outdir smartcard/scard -DWIN32 -o smartcard/scard/scard_wrap.c smartcard/scard/scard.i
      error: command 'swig.exe' failed: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyscard
  Running setup.py clean for pyscard
Failed to build pyscard
ERROR: Could not build wheels for pyscard, which is required to install pyproject.toml-based projects

**Comment by SteinRobert** [comment]
Hey @ODOshmocke this looks like a problem with [pyscard](https://github.com/LudovicRousseau/pyscard) or [swig](https://www.swig.org/Doc1.3/Python.html), not `python-healthcard`. I would recommend to work with Linux it's probably much easier to install there.
Not sure which windows you run but pyscard does not seem to support [modern versions](https://pyscard.sourceforge.io/user-guide.html#introduction).
If you can figure out how to install it on Windows feel free to submit a PR with a description (and if needed code changes).
